name: Trigger auto deployment for remy-gambit-ap

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/remy-gambit-ap-AutoDeployTrigger-bf9e51a5-46d6-4b6d-98fe-b20e42a48d57.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.REMYGAMBITAP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.REMYGAMBITAP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.REMYGAMBITAP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/api/Remy.Gambit.Api.Web
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: jasonmaglaya.azurecr.io
          registryUsername: ${{ secrets.REMYGAMBITAP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REMYGAMBITAP_REGISTRY_PASSWORD }}
          containerAppName: remy-gambit-ap
          resourceGroup: rg-remy
          imageToBuild: jasonmaglaya.azurecr.io/remy-gambit-ap:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


